#
# bashman : color index
#

_bashman_color_black=30
_bashman_color_red=31
_bashman_color_green=32
_bashman_color_yellow=33
_bashman_color_blue=34
_bashman_color_magenta=35
_bashman_color_cyan=36
_bashman_color_light_gray=37
_bashman_color_dark_gray=90
_bashman_color_light_red=91
_bashman_color_light_green=92
_bashman_color_light_yellow=93
_bashman_color_light_blue=94
_bashman_color_light_magenta=95
_bashman_color_light_cyan=96
_bashman_color_white=97
